### ISSUE TITLE
Error in exp function

### ISSUE THREAD

**Issue by creativefctr** [gburtini/PHP-Brute-Force-Defense#2]
Hi,
I get this error when trying to use  BFD:

Warning: exp() expects exactly 1 parameter, 2 given.

It's here, it appears that you might have wanted to use pow not exp: 

``` PHP
protected function eq($i) {
    if($i > $this->safe+$this->upper)
        $i = $this->safe+$this->upper;
        $timeout = min($this->maximumSleep,
                max($this->minimumSleep,
                    exp($this->rate, max(0, ($i - $this->safe)))
                )
        );
    return $timeout;
}
```

Thanks

**Comment by gburtini** [comment]
Sort of crazy that this slipped by. This code is in use on a number of projects. I must have fixed it in the project instead of in the core. My mistake.

**Comment by gburtini** [comment]
Wait, are you on the master branch? I see there is some funny tabs/spaces mix up in there that needs to be fixed, but the function calls pow in the latest commit to the master branch.

**Comment by gburtini** [comment]
Closing this, feel free to reopen it if I have erred.
